/*
Copyright 2020 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "knative.dev/eventing-github/pkg/apis/bindings/v1alpha1"
)

// FakeGitHubBindings implements GitHubBindingInterface
type FakeGitHubBindings struct {
	Fake *FakeBindingsV1alpha1
	ns   string
}

var githubbindingsResource = v1alpha1.SchemeGroupVersion.WithResource("githubbindings")

var githubbindingsKind = v1alpha1.SchemeGroupVersion.WithKind("GitHubBinding")

// Get takes name of the gitHubBinding, and returns the corresponding gitHubBinding object, and an error if there is any.
func (c *FakeGitHubBindings) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.GitHubBinding, err error) {
	emptyResult := &v1alpha1.GitHubBinding{}
	obj, err := c.Fake.
		Invokes(testing.NewGetActionWithOptions(githubbindingsResource, c.ns, name, options), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.GitHubBinding), err
}

// List takes label and field selectors, and returns the list of GitHubBindings that match those selectors.
func (c *FakeGitHubBindings) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.GitHubBindingList, err error) {
	emptyResult := &v1alpha1.GitHubBindingList{}
	obj, err := c.Fake.
		Invokes(testing.NewListActionWithOptions(githubbindingsResource, githubbindingsKind, c.ns, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.GitHubBindingList{ListMeta: obj.(*v1alpha1.GitHubBindingList).ListMeta}
	for _, item := range obj.(*v1alpha1.GitHubBindingList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested gitHubBindings.
func (c *FakeGitHubBindings) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchActionWithOptions(githubbindingsResource, c.ns, opts))

}

// Create takes the representation of a gitHubBinding and creates it.  Returns the server's representation of the gitHubBinding, and an error, if there is any.
func (c *FakeGitHubBindings) Create(ctx context.Context, gitHubBinding *v1alpha1.GitHubBinding, opts v1.CreateOptions) (result *v1alpha1.GitHubBinding, err error) {
	emptyResult := &v1alpha1.GitHubBinding{}
	obj, err := c.Fake.
		Invokes(testing.NewCreateActionWithOptions(githubbindingsResource, c.ns, gitHubBinding, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.GitHubBinding), err
}

// Update takes the representation of a gitHubBinding and updates it. Returns the server's representation of the gitHubBinding, and an error, if there is any.
func (c *FakeGitHubBindings) Update(ctx context.Context, gitHubBinding *v1alpha1.GitHubBinding, opts v1.UpdateOptions) (result *v1alpha1.GitHubBinding, err error) {
	emptyResult := &v1alpha1.GitHubBinding{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateActionWithOptions(githubbindingsResource, c.ns, gitHubBinding, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.GitHubBinding), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeGitHubBindings) UpdateStatus(ctx context.Context, gitHubBinding *v1alpha1.GitHubBinding, opts v1.UpdateOptions) (result *v1alpha1.GitHubBinding, err error) {
	emptyResult := &v1alpha1.GitHubBinding{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceActionWithOptions(githubbindingsResource, "status", c.ns, gitHubBinding, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.GitHubBinding), err
}

// Delete takes name of the gitHubBinding and deletes it. Returns an error if one occurs.
func (c *FakeGitHubBindings) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(githubbindingsResource, c.ns, name, opts), &v1alpha1.GitHubBinding{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeGitHubBindings) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionActionWithOptions(githubbindingsResource, c.ns, opts, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.GitHubBindingList{})
	return err
}

// Patch applies the patch and returns the patched gitHubBinding.
func (c *FakeGitHubBindings) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.GitHubBinding, err error) {
	emptyResult := &v1alpha1.GitHubBinding{}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceActionWithOptions(githubbindingsResource, c.ns, name, pt, data, opts, subresources...), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.GitHubBinding), err
}
