/*
Copyright 2020 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/listers"
	"k8s.io/client-go/tools/cache"
	v1alpha1 "knative.dev/eventing-github/pkg/apis/bindings/v1alpha1"
)

// GitHubBindingLister helps list GitHubBindings.
// All objects returned here must be treated as read-only.
type GitHubBindingLister interface {
	// List lists all GitHubBindings in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.GitHubBinding, err error)
	// GitHubBindings returns an object that can list and get GitHubBindings.
	GitHubBindings(namespace string) GitHubBindingNamespaceLister
	GitHubBindingListerExpansion
}

// gitHubBindingLister implements the GitHubBindingLister interface.
type gitHubBindingLister struct {
	listers.ResourceIndexer[*v1alpha1.GitHubBinding]
}

// NewGitHubBindingLister returns a new GitHubBindingLister.
func NewGitHubBindingLister(indexer cache.Indexer) GitHubBindingLister {
	return &gitHubBindingLister{listers.New[*v1alpha1.GitHubBinding](indexer, v1alpha1.Resource("githubbinding"))}
}

// GitHubBindings returns an object that can list and get GitHubBindings.
func (s *gitHubBindingLister) GitHubBindings(namespace string) GitHubBindingNamespaceLister {
	return gitHubBindingNamespaceLister{listers.NewNamespaced[*v1alpha1.GitHubBinding](s.ResourceIndexer, namespace)}
}

// GitHubBindingNamespaceLister helps list and get GitHubBindings.
// All objects returned here must be treated as read-only.
type GitHubBindingNamespaceLister interface {
	// List lists all GitHubBindings in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.GitHubBinding, err error)
	// Get retrieves the GitHubBinding from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.GitHubBinding, error)
	GitHubBindingNamespaceListerExpansion
}

// gitHubBindingNamespaceLister implements the GitHubBindingNamespaceLister
// interface.
type gitHubBindingNamespaceLister struct {
	listers.ResourceIndexer[*v1alpha1.GitHubBinding]
}
