name: "Kind e2e tests"
on:
  push:
    branches: [ 'master', 'release-*' ]
    pull_request:
      branches: [ 'master', 'release-*' ]
jobs:
  e2e-testing:
    name: GitHubSource Test
    runs-on: ubuntu-latest
    env:
      KO_DOCKER_REPO: kind.local
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Set up Go 1.15.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x
      - name: Install ko
        run: |
          GO111MODULE=on go get github.com/google/ko/cmd/ko@master
      - name: Install kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'v1.19.0'
      - name: Setup kind
        uses: engineerd/setup-kind@v0.4.0
        with:
          version: "v0.9.0"
          config: test/kind-config.yaml
      - name: Setup cluster
        run: |
          go test -v -count=1 ./test/... -timeout=15m -tags=e2e -setup=true
      - name: Run Tests
        run: |
          go test -v -race -timeout=15m -tags=e2e ./test/...

